<a href="https://colab.research.google.com/github/mallapureddykumith/100-days-data-analytics-learning-journey/blob/main/numpy_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#1
arr = np.array([10,20,30,40,50])
print(np.shape(arr))
print("______________")
print(np.ndim(arr))
print("______________")
print(np.size(arr))
print("______________")
print(arr.dtype)
print("______________")

#2
arr = np.arange(1,13)
print(arr)
print(arr.reshape(3,4))
arr = np.arange(1,25)
print(arr)
print(arr.reshape(2,3,4))

#3
arr = np.zeros(5)
print(arr)
arr = np.zeros((3, 4))
print(arr)
arr = np.zeros((3, 4, 3))
print(arr)

#4
arr = np.ones((2, 3))
print(arr)
print("Dimensions:", arr.ndim, "Shape:", arr.shape)

#5
arr = np.full((3, 4), 7)
print(arr)
matrix = np.eye(4)
print(matrix)

#6
arr = np.random.rand(5)
print(arr)
arr = np.random.rand(2, 3)
print(arr)

#7
arr = np.random.uniform(10, 50, (3, 3))
print(arr)

#8
arr = np.random.randn(2, 4)
print(arr)

#9
colours = ["Red","Blue","Green","Yellow","Black"]
arr = np.random.choice(colours, 3, replace=False)
print(arr)

#10
np.random.seed(42)
set1 = np.random.randint(1, 100, 5)
np.random.seed(42)
set2 = np.random.randint(1, 100, 5)
print(set1)
print(set2)
print("Both same:", np.array_equal(set1, set2))

#11
arr = np.arange(5, 51, 5)
print(arr)

#12
o_arr = np.array([10,20,30,40,50,60])
np.random.shuffle(o_arr)
print("Shuffled original:", o_arr)

o_arr2 = np.array([10,20,30,40,50,60])
p_arr = np.random.permutation(o_arr2)
print("Original:", o_arr2)
print("Shuffled copy:", p_arr)

#13
arr = np.linspace(0, 100, 6)
print(arr)

#14
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
matrix = arr.reshape(3, 4)
print(matrix)
arr1 = matrix.ravel()
print(arr1)

#15
arr = np.array([[1,2,3],[4,5,6]])
print("Transpose:\n", arr.T)
arr3d = arr.reshape(1,2,3)
print("3D:\n", arr3d)

#16
arr = np.array([10,20,30,40,50])
print("dtype:", arr.dtype)
arr = arr.astype(float)
print("float:", arr)
print("new dtype:", arr.dtype)


(5,)
______________
1
______________
5
______________
int64
______________
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[1. 1. 1.]
 [1. 1. 1.]]
Dimensions: 2 Shape: (2, 3)
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0.57846209 0.64766152 0.71132248 0.89202606 0.85090139]
[[0.27484056 0.96698234 0.51885504]
 [0.50172613 0.73616893 0.14891781]]
[[17.88337828 40.9489162  17.07584231]
 [13.67253577 23.33577494 24.66080441]
 [15.89342287 39.00621588 33.86255369]]
[[-0.20736686 -0.61583265 -0.55782685  1.74601